name = "smartsites360"
main = "worker.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

browser = { binding = "BROWSER" }

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
